# Nombre del workflow
name: Run Python Tests

# Trigger: Cuándo debe correr
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Descarga código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Instala las dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Corre los tests
      - name: Run tests with pytest
        run: pytest